create role  postgres  login ;
ALTER   ROLE   postgres   WITH   SUPERUSER ;
create table batch
(
    batch_key         integer generated by default as identity
        constraint batch_key
            primary key,
    created_at        timestamp with time zone,
    updated_at        timestamp with time zone,
    text_planned      varchar,
    text_completed    varchar,
    status            varchar,
    batch_size        integer,
    project_key       integer,
    batch_invoice_key integer
);

alter table batch
    owner to sumting;

create table batch_invoice
(
    batch_invoice_key  integer generated always as identity
        constraint batch_invoice_key
            primary key,
    amount_total       double precision,
    completed_at       timestamp with time zone,
    invoice_nr         varchar,
    invoice_unit_price double precision
);

alter table batch_invoice
    owner to sumting;

create table country
(
    country_key integer not null
        constraint pr_countries_pkey
            primary key,
    alpha2      varchar,
    alpha3      varchar,
    name        varchar,
    image_small varchar
);

alter table country
    owner to sumting;

create table order_type
(
    order_type_key bigint not null
        constraint ordertype_key
            primary key,
    description    varchar,
    order_type     varchar(255),
    is_ext         bit
);

alter table order_type
    owner to sumting;

create table partner
(
    partner_key integer generated always as identity
        constraint partner_pkey
            primary key,
    name        varchar,
    description varchar,
    created_at  timestamp with time zone,
    updated_at  timestamp with time zone,
    country     char(50),
    address     varchar,
    email       varchar,
    zipcode     varchar
);

alter table partner
    owner to sumting;

create table project
(
    project_key          integer generated always as identity
        constraint project_pkey
            primary key,
    description          varchar(255),
    description_long     varchar,
    created_at           timestamp with time zone,
    updated_at           timestamp with time zone,
    latitude             double precision,
    longitude            double precision,
    name                 varchar,
    project_image_medium "char",
    partner_key          integer
        constraint project_partner
            references partner,
    project_type_key     integer,
    batch_size_default   integer
);

alter table project
    owner to sumting;

create index fki_project_partner
    on project (partner_key);

create index fki_project_project_type
    on project (project_type_key);

create table "user"
(
    user_key       bigint generated always as identity
        constraint user_pkey
            primary key,
    user_name      varchar,
    email          varchar(255)             not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone,
    website        varchar(255),
    profile_image  varchar(255),
    profile_text   varchar(255),
    user_type      varchar(255),
    user_id_ext    bigint
        constraint unique_user_id_django
            unique,
    country_key    integer,
    user_stripe_id varchar,
    user_password  varchar(255),
    user_secret_code varchar(255),
    user_twofactor_enabled boolean
);

alter table "user"
    owner to sumting;

create table "order"
(
    order_key               bigint generated always as identity
        constraint order_key
            primary key,
    order_id_ext            integer not null,
    created_at              timestamp with time zone,
    payment_method          "char",
    payer_user_key          bigint
        constraint order_payer
            references "user",
    order_date              timestamp with time zone,
    description             varchar(255),
    order_stripe_payment_id varchar(255),
    transaction_total       double precision,
    order_type_key          integer
        constraint order_order_type
            references order_type,
    transaction_fee         double precision,
    transaction_vat         double precision,
    currency                char(5),
    user_id_ext             integer
);

alter table "order"
    owner to sumting;

create table orderline_giftcard
(
    orderline_key           bigint generated always as identity
        constraint orderline_giftcard_key
            primary key,
    order_key               bigint
        constraint orderline_giftcard_order_v2
            references "order",
    order_id_ext            bigint                   not null,
    quantity                integer,
    notes                   text,
    created_at              timestamp with time zone not null,
    updated_at              timestamp with time zone not null,
    transaction_line_total  double precision,
    expirated_at            date,
    token                   varchar,
    orderline_stripe_id     varchar,
    order_stripe_payment_id varchar,
    orderline_id_ext        varchar,
    product_key             integer[],
    product_id_ext          varchar
);

alter table orderline_giftcard
    owner to sumting;

create table product
(
    product_key       integer generated always as identity
        constraint product_pkey
            primary key,
    product_name      varchar,
    description       varchar,
    price             double precision,
    product_stripe_id varchar,
    web_flow_id       varchar,
    project_key       integer,
    product_type_key  integer,
    created_at        timestamp with time zone,
    updated_at        timestamp with time zone,
    product_id_ext    integer,
    is_active         boolean
);

alter table product
    owner to sumting;

create table product_type
(
    product_type_key  integer generated by default as identity
        constraint product_type_key
            primary key,
    product_type_name varchar,
    description       varchar,
    frequency         varchar,
    created_at        timestamp with time zone
);

alter table product_type
    owner to sumting;

create table project_price
(
    project_price_key integer generated always as identity
        constraint project_price_key
            primary key,
    project_key       integer,
    unit_price        double precision,
    unit_price_delta  double precision,
    created_at        timestamp with time zone,
    is_current        bit,
    project_price     double precision
);

alter table project_price
    owner to sumting;

create table project_type
(
    project_type_key integer generated always as identity
        constraint project_type_key
            primary key,
    description      varchar
);

alter table project_type
    owner to sumting;

create table wallet
(
    wallet_key       bigint generated always as identity
        constraint wallet_key
            primary key,
    balance          double precision,
    created_at       timestamp with time zone,
    updated_at       timestamp with time zone,
    payer_user_key   integer
        constraint wallet_user
            references "user",
    total_orderlines integer,
    owner_user_key   integer
);

alter table wallet
    owner to sumting;

create table orderline_contribution
(
    orderline_key           bigint generated always as identity
        constraint orderline_key
            primary key,
    order_key               bigint
        constraint orderline_order_v2
            references "order",
    order_id_ext            bigint not null,
    orderline_id_ext        varchar(256),
    quantity                integer,
    notes                   text,
    transaction_line_total  double precision,
    product_key             integer,
    product_id_ext          varchar,
    owner_user_key          integer
        constraint orderline_okey
            references "user",
    wallet_key              integer
        constraint orderline_wallet_v2
            references wallet,
    proof_name              varchar,
    proof_date              timestamp with time zone,
    latitude                double precision,
    longitude               double precision,
    proof_small             varchar,
    proof_medium            varchar,
    proof_large             varchar,
    batch_key               integer
        constraint orderline_batch_v2
            references batch,
    proof_uploaded_datetime timestamp with time zone,
    transaction_line_fee    double precision,
    transaction_line_vat    double precision,
    loaded_at               timestamp with time zone,
    unit_ref_line_item      varchar,
    orderline_stripe_id     varchar
);

alter table orderline_contribution
    owner to sumting;

