# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
stages:
  - build
  - test
  - deploy
  - docker

cache:
  paths:
    - target/
    - build/
variables:
  JDK_IMAGE: maven:3-openjdk-18


#Backend
build:backend:
  image: $JDK_IMAGE
  stage: build
  environment: production
  tags:
    - hva
  script:
    - echo "started building"
    - cd Backend
    - mvn clean install
    - mvn package -B -DskipTests=true
    - echo "Finished building"
  artifacts:
    paths:
      - target/*.jar #Save the jar file for the next stage
  only:
    - main

test:backend:
  image: $JDK_IMAGE
  stage: test
  tags:
    - hva
  needs:
    - job: build:backend
  script:
      - cd Backend #first cd into the backend folder
      - mvn $MAVEN_CLI_OPTS clean test -P unit-test
  artifacts:
    paths:
      - target/*.jar

##Frontend
build:frontend:
  image: node:latest
  tags:
    - hva
  stage: build
  script:
     - cd frontend
     - npm install --progress=false
     - npm run build
  artifacts:
     paths:
       - dist

test:frontend:
  image: node:latest
  stage: test
  tags:
    - hva
  script:
    - cd frontend
    - npm install --progress=false
  needs:
    - job: build:frontend

docker:build:
  environment: production
  image: docker:stable
  stage: docker
  needs:
    - job: build:backend
    - job: build:frontend
    - job: test:frontend
    - job: test:backend
  tags:
    - hva
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_HUB $DOCKER_IMAGE
    - docker-compose build
    - docker-compose push
    - echo "Images builded"
  only:
    - main


##Deploy to Prod server
deploy:prod:
  environment: production
  image: ubuntu:latest
  stage: deploy
  needs:
    - job: build:backend
    - job: build:frontend
    - job: test:frontend
    - job: test:backend
  rules:
    - if: $CI_COMMIT_TAG
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    name: 'Sumting Admin panel Release'
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
  tags:
    - hva
  before_script:
    - echo "Deploying!"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_HUB $DOCKER_IMAGE
    - docker-compose -H "ssh://admin@$SERVER" down --remove-orphans
    - docker-compose -H "ssh://admin@$SERVER" pull
    - docker-compose -H "ssh://admin@$SERVER" up -d
