version: '3.6'
services:
  db:
    image: gitlab.fdmci.hva.nl:5050/se-ewa/2022-2023-1/sum-1/db
    build:
      context: ./Docker/postgres
      dockerfile: Dockerfile
    restart: always
    hostname: postgres
    container_name: sumting-docker-db
    environment:
      POSTGRES_PASSWORD: sumting
      POSTGRES_USER: sumting
      POSTGRES_DB: sumting
    volumes:
       - ./data/db:/var/lib/postgresql/data
       - ./Docker/postgres/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
         # copy the sql script to fill tables
       - ./Docker/postgres/example_data.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sumtingDb
      - nginxproxymanager_default
    expose:
      - "5432"
  back:
    image: gitlab.fdmci.hva.nl:5050/se-ewa/2022-2023-1/sum-1/sumting-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: sumting-admin-backend
    depends_on:
      - db

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sumting
      - SPRING_DATASOURCE_USERNAME=sumting
      - SPRING_DATASOURCE_PASSWORD=sumting
    restart: always
    ports:
      - "8083:8083"
    networks:
      - sumting
      - sumtingDb
      - nginxproxymanager_default

    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  front:
    image: gitlab.fdmci.hva.nl:5050/se-ewa/2022-2023-1/sum-1/sumting-frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NGINX_HOST=sumting.pdik.nl
      - VUE_APP_BACKEND_API_URL=https://sumting.pdik.nl/api
      - VUE_APP_ENV=production
    networks:
      - sumting
      - nginxproxymanager_default
#    ports:
#      - "80:80"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  data:

networks:
  sumtingDb:
    driver: bridge
  sumting:
    driver: bridge
  nginxproxymanager_default:
    external: true
